// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSmifKUGgz5qqtKnZD92Hd36nhWO3xoZA',
    appId: '1:73797710109:web:d958fa66cf152cb6a0f1f4',
    messagingSenderId: '73797710109',
    projectId: 'studykatta-7ed3b',
    authDomain: 'studykatta-7ed3b.firebaseapp.com',
    databaseURL: 'https://studykatta-7ed3b-default-rtdb.firebaseio.com',
    storageBucket: 'studykatta-7ed3b.appspot.com',
    measurementId: 'G-F7SQLB6WFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWurIPYrkQi6RTnGF1b9ZDJIkht7FfDJI',
    appId: '1:73797710109:android:b3666c10283c1d91a0f1f4',
    messagingSenderId: '73797710109',
    projectId: 'studykatta-7ed3b',
    databaseURL: 'https://studykatta-7ed3b-default-rtdb.firebaseio.com',
    storageBucket: 'studykatta-7ed3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKI3YEslUfGEBaizpHYqnsbSnaf0JjzE8',
    appId: '1:73797710109:ios:d6296e001c0cbe45a0f1f4',
    messagingSenderId: '73797710109',
    projectId: 'studykatta-7ed3b',
    databaseURL: 'https://studykatta-7ed3b-default-rtdb.firebaseio.com',
    storageBucket: 'studykatta-7ed3b.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKI3YEslUfGEBaizpHYqnsbSnaf0JjzE8',
    appId: '1:73797710109:ios:03dd524dedb97e7fa0f1f4',
    messagingSenderId: '73797710109',
    projectId: 'studykatta-7ed3b',
    databaseURL: 'https://studykatta-7ed3b-default-rtdb.firebaseio.com',
    storageBucket: 'studykatta-7ed3b.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
